SELECT b.AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM(PRICE*SALES)TOTAL_SALES
FROM BOOK b
LEFT JOIN AUTHOR a
ON b.AUTHOR_ID=a.AUTHOR_ID
RIGHT JOIN BOOK_SALES s
ON s.BOOK_ID=b.BOOK_ID
WHERE TO_CHAR(sales_date,'YYYY-MM')='2022-01'
GROUP BY b.AUTHOR_ID,AUTHOR_NAME,CATEGORY
ORDER BY b.AUTHOR_ID,CATEGORY DESC;