WITH temp AS(
    SELECT car_id
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_DATE('20221016','YYYYMMDD') BETWEEN START_DATE	AND END_DATE    
)

SELECT car_id,
CASE
    WHEN EXISTS(SELECT car_id FROM temp WHERE car_id=t.car_id) THEN '대여중'
    ELSE '대여 가능'
END AVAILABILITY
FROM
(SELECT car_id
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY car_id)t
ORDER BY car_id DESC; 

