-- 코드를 입력하세요
SELECT u.user_id,(SELECT NICKNAME FROM USED_GOODS_USER WHERE USER_ID=u.USER_ID)NIKENAME,SUM(PRICE)TOTAL_SALES
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u
ON b.WRITER_ID=u.user_id
WHERE status='DONE'
GROUP BY u.user_id
HAVING SUM(PRICE)>=700000
ORDER BY TOTAL_SALES;