SELECT p.MEMBER_NAME,r.REVIEW_TEXT,TO_CHAR(r.REVIEW_DATE,'YYYY-MM-DD')REVIEW_DATE
FROM REST_REVIEW r
FULL JOIN MEMBER_PROFILE p
ON r.MEMBER_ID=p.MEMBER_ID
WHERE p.MEMBER_ID IN (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*)=(
SELECT MAX(COUNT(*))
FROM REST_REVIEW
GROUP BY MEMBER_ID
))
ORDER BY r.REVIEW_DATE,r.REVIEW_TEXT;


