WITH temp AS(
    SELECT CAR_ID,COUNT(*)records
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(start_date,'YYYY-MM')IN('2022-08','2022-09','2022-10')
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
)

SELECT TO_NUMBER(TO_CHAR(start_date,'MM'))month,CAR_ID,COUNT(*)records
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
WHERE TO_CHAR(start_date,'YYYY-MM')IN('2022-08','2022-09','2022-10')
GROUP BY TO_CHAR(start_date,'MM'),CAR_ID
HAVING EXISTS(SELECT * FROM temp
              WHERE car_id =c.car_id)
ORDER BY month,CAR_ID DESC;
