-- 코드를 입력하세요
SELECT u.TITLE,u.BOARD_ID,r.REPLY_ID,r.WRITER_ID,r.CONTENTS,TO_CHAR(r.CREATED_DATE,'YYYY-MM-DD')CREATED_DATE 
FROM USED_GOODS_BOARD u
JOIN USED_GOODS_REPLY r
ON u.BOARD_ID=r.BOARD_ID
WHERE TO_CHAR(u.CREATED_DATE,'YYYY-MM')='2022-10'
ORDER BY r.CREATED_DATE,u.TITLE;